
/*==========================================================
  1. EXPLORE THE DATABASE
  ==========================================================*/

-- Display all tables in the current database
SHOW TABLES;

-- Display the structure of the Products table
DESC products;

-- Display all customer records
SELECT *
FROM customers;

-- Display all product records
SELECT *
FROM products;


/*==========================================================
  2. FILTERING USING WHERE CLAUSE
  ==========================================================*/

-- Retrieve all delivered orders
SELECT *
FROM orders
WHERE status = 'Delivered';

-- Retrieve Electronics products costing more than ₹2000
SELECT *
FROM products
WHERE category = 'Electronics'
AND unit_price > 2000;

-- Retrieve customers from Maharashtra
SELECT *
FROM customers
WHERE state = 'Maharashtra';


/*==========================================================
  3. AGGREGATION FUNCTIONS
  ==========================================================*/

-- Calculate total revenue from delivered orders
SELECT
SUM(total_amount) AS Total_Revenue
FROM orders
WHERE status = 'Delivered';

-- Calculate average product price by category
SELECT
category,
AVG(unit_price) AS Average_Price
FROM products
GROUP BY category;

-- Count orders and revenue by order status
SELECT
status,
COUNT(*) AS Total_Orders,
SUM(total_amount) AS Revenue
FROM orders
GROUP BY status
ORDER BY Revenue DESC;


/*==========================================================
  4. SORTING & LIMIT
  ==========================================================*/

-- Display Top 5 most expensive products
SELECT *
FROM products
ORDER BY unit_price DESC
LIMIT 5;


/*==========================================================
  5. BUSINESS ANALYSIS USING JOINS
  ==========================================================*/

-- Find top customers based on total spending
SELECT
    c.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS Customer_Name,
    SUM(o.total_amount) AS Total_Spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, Customer_Name
ORDER BY Total_Spent DESC;


-- Find best-selling products based on quantity sold
SELECT
    p.product_name,
    SUM(oi.quantity) AS Quantity_Sold
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY Quantity_Sold DESC;


-- Calculate revenue generated by each product category
SELECT
    p.category,
    SUM(oi.quantity * oi.unit_price) AS Revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY Revenue DESC;


/*==========================================================
  6. DATA VALIDATION
  ==========================================================*/

-- Verify total number of records in each table
SELECT
(SELECT COUNT(*) FROM customers) AS Customers,
(SELECT COUNT(*) FROM products) AS Products,
(SELECT COUNT(*) FROM orders) AS Orders,
(SELECT COUNT(*) FROM order_items) AS Order_Items;


/*==========================================================
  7. CHECK FOR DUPLICATE EMAILS
  ==========================================================*/

SELECT
email,
COUNT(*) AS Duplicate_Count
FROM customers
GROUP BY email
HAVING COUNT(*) > 1;


/*==========================================================
  8. CHECK FOR INVALID PRODUCT PRICES
  ==========================================================*/

SELECT *
FROM products
WHERE unit_price <= 0;


/*==========================================================
  9. COMPLETE ORDER DETAILS USING MULTIPLE JOINS
  ==========================================================*/

SELECT
    o.order_id,
    o.order_date,
    CONCAT(c.first_name,' ',c.last_name) AS Customer_Name,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.discount_pct
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN products p
ON oi.product_id = p.product_id
ORDER BY o.order_id;


/*==========================================================
  END OF ASSIGNMENT
  ==========================================================*/